```{r}
olympics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-08-06/olympics.csv')
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
swimming <- olympics %>%
  filter(sport == "Swimming")%>%
  drop_na()
swimming
```


```{r}
ggplot(swimming, aes(x = team))+
  geom_bar()
```

```{r}
swimming_year <- swimming%>%
  group_by(year)%>%
  summarize(avg_h = mean(height),
         avg_w = mean(weight),
         avg_a = mean(age))
ggplot(swimming_year, aes(x = year, y = avg_h))+
  geom_point()
ggplot(swimming_year, aes(x = year, y = avg_w))+
  geom_point()
ggplot(swimming_year, aes(x = year, y = avg_a))+
  geom_point()
```


```{r}
swimming_event <- swimming %>%
  group_by(event)%>%
  summarize(avg_h = mean(height),
            avg_w = mean(weight),
            avg_a = mean(age),
            count = n())%>%
  slice_max(count, n=10)
ggplot(swimming, aes(x = event))+
  geom_bar()
ggplot(swimming_event, aes(x = event, y = avg_h))+
  geom_point()
ggplot(swimming_event, aes(x = event, y = avg_w))+
  geom_point()
ggplot(swimming_event, aes(x = event, y = avg_a))+
  geom_point()
```


```{r}
shooting <- olympics %>%
  filter(sport == "Shooting")%>%
  drop_na()
shooting

rowing<- olympics %>%
  filter(sport == "Rowing")%>%
  drop_na()
rowing
```

```{r}
ggplot(shooting, aes(x = fct_infreq(team)))+
  
  geom_bar()
```


```{r}
ggplot(rowing, aes(x = fct_infreq(team)))+
  geom_bar()
```





